- hosts: terraform-ansible
  tasks: 
  - name: Instalando o Python 3, virtualenv
    apt:
      pkg: 
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias
    pip:
      virtualenv: /home/ubuntu/gether/venv
      name:
        - django
        - djangorestframework