$ansibleInstall = <<-SCRIPT
  apt-get update && \
  apt-get install -y software-properties-common && \
  apt-add-repository --yes --update ppa:ansible/ansible &&\
  apt-get install -y ansible
SCRIPT

$copiaKey = <<-SCRIPT
  cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys
SCRIPT

$installDocker = <<-SCRIPT
  apt-get update && \
  apt-get install -y docker.io
SCRIPT

$ansibleKey = <<-SCRIPT
  cp /vagrant/id_rsa /home/vagrant && \
  chmod 600 /home/vagrant/id_rsa && \
  chown vagrant:vagrant /home/vagrant/id_rsa
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  # config.vm.define "dockerhost" do |dockerhost|
  #   dockerhost.vm.network "public_network", ip: "192.168.1.28"

  #   dockerhost.vm.provider "virtualbox" do |vb|
  #     vb.name = "ubuntu_dockerhost"   
  #   end

  #   dockerhost.vm.provision "shell", inline: $copiaKey

  #   dockerhost.vm.provision "shell",
  #     inline: $installDocker
  # end

  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.network "public_network", ip: "192.168.1.22"

    wordpress.vm.provision "shell", inline: "cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys"    
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "public_network", ip: "192.168.1.24"

    mysql.vm.provision "shell", inline: "cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.26"

    ansible.vm.provision "shell", inline: $copiaKey
    ansible.vm.provision "shell", inline: $ansibleKey

    ansible.vm.provision "shell", 
      inline: $ansibleInstall

    ansible.vm.provision "shell", 
      inline: "ansible-playbook -i /vagrant/configs/hosts\
               /vagrant/configs/provisioning.yml"
  end
end