---
- name: 'Instala pacotes'
  apt:
    name: 
      - mysql-server-5.7
      - python3-mysqldb
    state: latest
  become: yes  

- name: 'Cria banco Mysql'    
  mysql_db: 
    name: "{{ wp_db_name }}"
    login_user: root
    login_password: "{{ wp_db_pass }}"
    state: present
  become: yes

- name: 'Cria usuário'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"        
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ wp_host_ip }}"
  become: yes

- name: 'Copiar arquivo mysqld.cnf'
  copy:
    src: /vagrant/configs/roles/mysql/files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - restart mysql