---
- hosts: all
  tasks:
    - name: 'Isntala pacotes'
      apt:
        name: 
          - php7.2
          - apache2
          - libapache2-mod-php7.2
          - php7.2-gd
          - libssh-4
          - mysql-server-5.7
          - python3-mysqldb
          - php7.2-mysql
        state: latest
      become: yes  
    - name: 'Cria banco Mysql'    
      mysql_db: 
        name: wordpress_db
        login_user: root
        login_password: pass        
        state: present
      become: yes
    - name: 'Cria usuário'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: pass
        priv: 'wordpress_db.*:ALL'        
        state: present
      become: yes